export const webFrameworkNames = [
  'Next.js',
  'React',
  'Vue',
  'Svelte',
  'Python',
  'Angular',
  'Nuxt',
  'Other',
  'Gatsby',
  'Ember.js',
  'Backbone.js',
  'Laravel',
  'Django',
  'Flask',
  'Ruby on Rails',
  'ASP.NET',
  'Express.js',
  'Meteor',
   'Other'
];

export const cssPackages = [
  'CSS',
  'Bootstrap',
  'Tailwind CSS',
  'Material-UI',
  'Bulma',
  'Semantic UI',
  'Foundation',
  'Ant Design',
  'UIKit',
  'Skeleton',
  'Styled Components',
  'Others',
  'LESS',
  'Sass',
  'PostCSS',
  'Tachyons',
  'Milligram',
  'Pure CSS',
  'Stylus',
  'CSS Modules',
  'Emotion',
  'Radium',
   'Other'
];

export const useCases = [
  'Blog',
  'CMS',
  'Community Sites',
  'Content-driven websites',
  'Cron Jobs',
  'Documentation',
  'Edge Functions',
  'Edge Middleware',
  'Ecommerce',
  'Landing Pages',
  'Marketing Sites',
  'Monorepos',
  'Multi-tenant Apps',
  'Portfolio',
  'Real-time Apps',
  'SaaS',
  'Virtual Events',
  'Business Websites',
  'News Websites',
  'Personal Blogs',
  'Forums',
  'Learning Management Systems (LMS)',
  'Social Media Platforms',
  'Job Boards',
  'Q&A Websites',
  'Crowdfunding Platforms',
  'Streaming Services',
  'Other'
];
